- name: Ansible-Activity
  remote_user: ubuntu
  hosts: servers
  gather_facts: false
  vars:
    ansible_host_key_checking: false

  pre_tasks:
    - name: Wait 60 seconds for instances to become alive
      wait_for_connection:
        timeout: 60

  roles:
    - configure
    - deploy
